# Generated by Django 5.1 on 2024-10-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Haber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('icerik', models.TextField()),
                ('yazar', models.CharField(max_length=100)),
                ('yayinlanma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
