# Generated by Django 5.1 on 2024-10-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haber', '0002_kategori_haber_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='haber',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to='haber_resimleri/'),
        ),
    ]
