# Generated by Django 5.1 on 2024-10-30 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haber', '0004_remove_haber_resim_resim'),
    ]

    operations = [
        migrations.AddField(
            model_name='haber',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to='haber_resimleri/'),
        ),
        migrations.AlterField(
            model_name='haber',
            name='kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='haberler', to='haber.kategori'),
        ),
        migrations.DeleteModel(
            name='Resim',
        ),
    ]
