# Generated by Django 5.1 on 2024-11-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haber', '0007_haber_on_bilgi'),
    ]

    operations = [
        migrations.AddField(
            model_name='haber',
            name='aktif',
            field=models.BooleanField(default=True),
        ),
    ]
